name: Teplitsa application

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Stop previous containers
              run: docker compose -f ./docker/compose.yaml down

            - name: Build and run containers
              run: |
                  echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> ./docker/.env
                  echo "OPENWEATHER_KEY=${{ secrets.OPENWEATHER_KEY }}" >> ./docker/.env
                  echo "OPENAI_SUMMARY_KEY=${{ secrets.OPENAI_SUMMARY_KEY }}" >> ./docker/.env
                  echo "OPENAI_VALIDATOR_KEY=${{ secrets.OPENAI_VALIDATOR_KEY }}" >> ./docker/.env
                  echo "DGIS_KEY=${{ secrets.DGIS_KEY }}" >> ./docker/.env
                  docker compose -f ./docker/compose.yaml up -d --build
